### ISSUE TITLE
[stage] Errno::ESTALE: Stale file handle

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#157]
dor-services-app is getting these error messages:

```
Errno::ESTALE: Stale file handle @ utime_internal - /purl/recent_changes/pd507wn8117
```

It's possible we have a race condition between purl-fetcher's listener (renaming/deleting the file) and the publish robot (touching the file) on an NFS filesystem.

```
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:1153:in `utime'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:1153:in `block in touch'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:1150:in `each'
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:1150:in `touch'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.10.0/lib/dor/models/publishable.rb:87:in `publish_not
ify_on_success'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/dor-services-5.10.0/lib/dor/models/publishable.rb:65:in `publish_met
adata'
/home/lyberadmin/dor-services-app/releases/20160817185754/lib/dor_services_app.rb:203:in `block (4 levels) in <class:DorServicesApi>
'
/home/lyberadmin/dor-services-app/shared/bundle/ruby/2.2.0/gems/grape-0.14.0/lib/grape/endpoint.rb:67:in `call'
```

It's possible that `FileUtils.touch` is not atomic over NFS -- see https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/publishable.rb#L87 -- and that we might need to switch to `File.write`

Also @eefahy we may need to disable `noac` on the purl-fetcher NFS mounts.

**Comment by drh-stanford** [comment]
See http://stackoverflow.com/questions/8100574/creating-an-empty-file-in-ruby-touch-equivalent

**Comment by drh-stanford** [comment]
Looks like we can tune the listener to delay the callbacks.

```
latency: 0.5                                    # Set the delay (**in seconds**) between checking for changes
                                                # default: 0.25 sec (1.0 sec for polling)

wait_for_delay: 4                               # Set the delay (**in seconds**) between calls to the callback when changes exist
                                                # default: 0.10 sec
```

**Comment by drh-stanford** [comment]
so I think we have the following options thus far:

For Publishable:
* keep as-is (using `FileUtils.touch(fn)`)
* use `File.open(fn, 'w') {}`
* use `FileUtils.touch("fn.tmp"); FileUtils.mv(...)` and add ignore *.tmp to listener
* use `system('touch fn')` (as lame as that is)

For Listener:
* adjust the latency and wait_for_delay on the `listen` gem to slow down the exposure of the race condition
* add explicit sleep in our processing to slow down exposure

**Comment by drh-stanford** [comment]
The PR for this was merged... we need to deploy `master` to production

**Comment by drh-stanford** [comment]
deployed to production
