### ISSUE TITLE
scale testing in prod

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/purl-fetcher#91]
Copy `/purl/document_cache` data from prod into dev to test find and indexing and listener at scale.

**Comment by drh-stanford** [comment]
We discussed just doing the scale testing in prod.

**Comment by drh-stanford** [comment]
Deployed 2.0.0 to prod and running `find:all` now for scale testing

**Comment by drh-stanford** [comment]
The `find` command took 8 hours to run, and the indexing is still going -- 17 hours into it, it has about 50k more PURLs to go.

```
2.3.0 :002 > Purl.count
 => 694211 
2.3.0 :003 > 
[lyberadmin@purl-fetcher-prod current]$ wc -l log/purl_finder_2016-08-18_19-30-56-778.txt 
741925 log/purl_finder_2016-08-18_19-30-56-778.txt
```

**Comment by drh-stanford** [comment]
Here are the NFS client stats:

```
[lyberadmin@purl-fetcher-prod current]$ nfsstat 
Client rpc stats:
calls      retrans    authrefrsh
485814190   5          486324115

Client nfs v3:
null         getattr      setattr      lookup       access       readlink     
0         0% 3707738906 40% 1         0% 324050210  3% 2515379851 27% 0         0% 
read         write        create       mkdir        symlink      mknod        
4438756   0% 0         0% 0         0% 0         0% 0         0% 0         0% 
remove       rmdir        rename       link         readdir      readdirplus  
0         0% 0         0% 0         0% 0         0% 2543848   0% 2519772307 27% 
fsstat       fsinfo       pathconf     commit       
1845772   0% 6         0% 3         0% 0         0% 
```

**Comment by drh-stanford** [comment]
The box is largely idle during the parsing and database saving -- it could be parallelized:

```
[lyberadmin@purl-fetcher-prod current]$ vmstat 1
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0 202728 459432 263700 1248796    1    0     7     2    0    0  1  2 96  0  0	
 2  0 202728 459688 263700 1248840    0    0     0   200 1409 1632 17  1 77  5  0	
 1  0 202728 459952 263700 1248888    0    0     0   236 1136 1470 11  2 83  4  0	
 0  1 202728 459812 263704 1248932    0    0     0   224  967 1401 11  2 83  5  0	
 0  1 202728 459176 263704 1248980    0    0     0   180 1102 1495 10  4 83  4  0	
```

**Comment by drh-stanford** [comment]
there may be a slight file descriptor leak (or slowness in closing them) somewhere?

```
ruby    26661 lyberadmin    0u   CHR              136,2      0t0         5 /dev/pts/2
ruby    26661 lyberadmin    1u   CHR              136,2      0t0         5 /dev/pts/2
ruby    26661 lyberadmin    2u   CHR              136,2      0t0         5 /dev/pts/2
ruby    26661 lyberadmin    3r  FIFO                0,8      0t0 818228386 pipe
ruby    26661 lyberadmin    4w  FIFO                0,8      0t0 818228386 pipe
ruby    26661 lyberadmin    5r  FIFO                0,8      0t0 818228387 pipe
ruby    26661 lyberadmin    6w  FIFO                0,8      0t0 818228387 pipe
ruby    26661 lyberadmin    7w   REG              253,4 31654168     98327 /var/log/purl-fetcher/indexing.log
ruby    26661 lyberadmin    8w   REG              253,4   118724     98326 /var/log/purl-fetcher/production.log
ruby    26661 lyberadmin    9u  unix 0xffff88007f9c4180      0t0 818228472 socket
ruby    26661 lyberadmin   10r   REG              253,4 31902775     98331 /var/log/purl-fetcher/purl_finder_2016-08-18_19-30-56-778.txt
ruby    26661 lyberadmin   12r   REG               0,21     3325   8770142 /purl/document_cache/rs/994/nn/0285/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   13r   REG               0,21     2654  10075185 /purl/document_cache/rs/482/pq/6478/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   14r   REG               0,21     6288   5106104 /purl/document_cache/rs/309/hc/5937/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   15r   REG               0,21     3024   5145006 /purl/document_cache/rs/249/rt/6510/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   16r   REG               0,21     3024   7757614 /purl/document_cache/rs/904/kd/5141/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   17r   REG               0,21     3024   7064742 /purl/document_cache/rs/413/mw/1299/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   18r   REG               0,21     3286   3554516 /purl/document_cache/rs/482/rb/6245/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   19r   REG               0,21     3384   8770132 /purl/document_cache/rs/913/sj/7582/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   20r   REG               0,21     4381   6833646 /purl/document_cache/rs/249/zy/6778/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   21r   REG               0,21     3739   8787971 /purl/document_cache/rs/544/fs/1656/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   22r   REG               0,21     2632   6397761 /purl/document_cache/rs/845/nt/6986/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   23r   REG               0,21     3330   6665673 /purl/document_cache/rs/845/vs/5586/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   25r   REG               0,21     3306   8787961 /purl/document_cache/rs/309/bc/9182/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   26r   REG               0,21     3340   8821246 /purl/document_cache/rs/539/jg/3311/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   27r   REG               0,21     3663   8821256 /purl/document_cache/rs/084/ry/7689/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   28r   REG               0,21     3528   9312779 /purl/document_cache/rs/994/jp/3957/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   29r   REG               0,21     3820   8314197 /purl/document_cache/rs/413/wd/1185/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   30r   REG               0,21     5050   6370215 /purl/document_cache/rs/913/cq/4333/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
ruby    26661 lyberadmin   33r   REG               0,21     5503   4582279 /purl/document_cache/rs/904/bh/7588/public (sf4-webapp:/vol/sul_purl_prod/document_cache)
```

**Comment by drh-stanford** [comment]
```
I, [2016-08-19T14:15:30.403323 #26661]  INFO -- : Ran 'find:changes[]' in 92674 seconds
I, [2016-08-19T14:26:22.932964 #26661]  INFO -- : Ran 'find:deletes[]' in 653 seconds
```

**Comment by drh-stanford** [comment]
```
[lyberadmin@purl-fetcher-prod current]$ RAILS_ENV=production bundle exec rails console
Loading production environment (Rails 4.2.7.1)
2.3.0 :001 > Purl.count
 => 762840 
2.3.0 :002 > Purl.where.not(deleted_at: nil).count
 => 20954 
2.3.0 :003 > Purl.where(deleted_at: nil).count
 => 741886 
2.3.0 :004 > 
[lyberadmin@purl-fetcher-prod current]$ wc -l log/purl_finder_2016-08-18_19-30-56-778.txt 
741925 log/purl_finder_2016-08-18_19-30-56-778.txt
```

There looks like 39 PURLs in production that are throwing errors.

Here's a partial list of them:

```
cc194nr5321 cw795zs2349 dp217ht0877 dy685nf4395 fj096ht7467 fr073zv0724
fz858hd6588 gq329fs9022 gr137tg0292 jv979fw8535 km097rd5656 ks485yz2876
md225cb2391 mr497sx5638 nd109dt4068 ns433mb7781 pt254ff9966 py409cp8971
rb069xm8239 rf468nq4709 rs788cb1324 tg006fh6427 wf048nx0420 wf977zr5113
ws392nq4863 wy046qm4273 wy436sg2226
```

the exception is 
```
I, [2016-08-19T12:52:57.710903 #26661]  INFO -- : indexing wf048nx0420
E, [2016-08-19T12:52:57.774590 #26661] ERROR -- : An error occurred while trying to save wf048nx0420.  
undefined method `attr' for nil:NilClass 
["/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/lib/purl_parser.rb:45:in `druid'", "/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/app/models/purl.rb:17:in `save_from_public_xml'", "/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/lib/purl_finder.rb:89:in `block in index_purls'", "/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/lib/purl_finder.rb:84:in `foreach'", "/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/lib/purl_finder.rb:84:in `index_purls'", "/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/lib/purl_finder.rb:45:in `find_and_index'", "/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/lib/tasks/find.rake:16:in `block (3 levels) in <top (required)>'", "/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'", "/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/lib/tasks/find.rake:15:in `block (2 levels) in <top (required)>'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'", "/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'", "/opt/app/lyberadmin/purl-fetcher/releases/20160818192745/lib/tasks/find.rake:8:in `block (2 levels) in <top (required)>'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'", "/opt/app/lyberadmin/purl-fetcher/shared/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb::
```

**Comment by drh-stanford** [comment]
Closing this barring any objections. 

See #139 for the query slowness.
